### ISSUE TITLE
animation to show up

### ISSUE THREAD

**Issue by jjhesk** [developer-shivam/Diagonalify#2]
any plans on integration of revealing animation?

**Comment by developer-shivam** [comment]
No plans yet to add a reveal animation but its a nice feature. I'll think about it that where to add this animation.

**Comment by jjhesk** [comment]
does it allow changing the angles and all other configurations after the xml is initiated?

**Comment by developer-shivam** [comment]
Yes you can change other configuration. Also you can animate angle with value animator like increasing angle from 0 to 15.
